title=images/title.png
game.over=images/game_over.png
game.guide=images/Pictures/game_guide.png
item.guide=images/Pictures/item_guide.png
status.panel=images/Pictures/status_panel.png
player.red=images/Characters/player_red.png
player.duck=images/Characters/player_duck.png
bubble=images/Characters/bubble.png
bubble.trap=images/Characters/bubble_trap.png
obstacles=images/Characters/obstacles.png
bubble.item=images/Characters/bubble_item.png
potion.blue=images/Characters/potion_blue.png
antidote=images/Characters/antidote.png
remote=images/Characters/remote.png
water.mine=images/Characters/water_mine.png
demon.red=images/Characters/demon_red.png
demon.purple=images/Characters/demon_purple.png
card.gold=images/Characters/card_gold.png
card.diamond=images/Characters/card_diamond.png
water.blast=images/water_blast.png
